### ISSUE TITLE
Autoban for league of legends players

### ISSUE THREAD

**Issue by ZubatyNos** [YelovSK/Spaghett_bot#1]
like so
![image](https://user-images.githubusercontent.com/59411496/151961562-f2fdaecd-6a2d-4948-a4f8-5d42acbaa6ba.png)

**Comment by YelovSK** [comment]
https://github.com/YelovSK/Spaghett_bot/commit/6e71bdd9ad85ff6ca8b9c213cd4545b60a527943 thank you for the suggestion

**Comment by YelovSK** [comment]
https://github.com/YelovSK/Spaghett_bot/commit/af160483321a111080c0fd17c45b15d54c4e0843
